name: Trigger Buildkite Build
on:
  push:
    branches:
      - main
jobs:
  trigger_buildkite:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Buildkite Build
        env:
          BUILDKITE_API_TOKEN: ${{ secrets.BUILDKITE }}
        run: |
          curl -X POST "https://api.buildkite.com/v2/organizations/hazenai/pipelines/buildkite-github-action-test/builds" \
            -H "Content-Type: application/json" \
            -d "commit=${{ github.sha }}" \
            -H "Authorization: Bearer $BUILDKITE_API_TOKEN"
