name: Trigger Buildkite Build
on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger_buildkite:
    if: startsWith(github.event.comment.body, '/buildkite')
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR information
        id: pr_info
        run: |
          COMMENT_BODY=$(echo "${{ github.event.comment.body }}")
          SHA=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $1}')
          BRANCH=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $2}')
          echo "::set-env name=SHA::${SHA}"
          echo "::set-env name=BRANCH::${BRANCH}"
      - name: Trigger Buildkite Build
        env:
          BUILDKITE_API_TOKEN: ${{ secrets.bkua_cddacd54a5426d0104266813f7ec3c037a3ade64 }}
          SHA: ${{ env.SHA }}
          BRANCH: ${{ env.BRANCH }}
        run: |
          curl -X POST "https://api.buildkite.com/v2/organizations/hazenai/pipelines/buildkite-github-action-test/builds" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $BUILDKITE_API_TOKEN" \
            -d "{\"commit\":\"${SHA}\", \"branch\":\"${BRANCH}\"}"
