name: Trigger Buildkite Build
on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger_buildkite:
    if: startsWith(github.event.comment.body, '/buildkite')
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR information
        id: pr_info
        run: |
          echo "::set-output name=sha::$(jq -r .comment.body <<< '${{ github.event }}' | grep -oP '(?<=\b/buildkite\s).*' | tr -d '"')"
          echo "::set-output name=branch::$(jq -r '.issue.pull_request.head.ref' <<< '${{ github.event }}')"
      - name: Trigger Buildkite Build
        env:
          BUILDKITE_API_TOKEN: ${{ secrets.bkua_cddacd54a5426d0104266813f7ec3c037a3ade64 }}
        run: |
          curl -X POST "https://api.buildkite.com/v2/organizations/hazenai/pipelines/buildkite-github-action-test/builds" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer bkua_cddacd54a5426d0104266813f7ec3c037a3ade64" \
            -d '{"commit":"'"${{ steps.pr_info.outputs.sha }}"'", "branch":"'"${{ steps.pr_info.outputs.branch }} "'"}'
