name: Trigger Buildkite Build
on:
  issue_comment:
    types: [created, edited]

jobs:
  trigger_buildkite:
    if: startsWith(github.event.comment.body, '/buildkite')
    runs-on: ubuntu-latest
    env:
      SHA: ""
      BRANCH: ""
    steps:
      - name: Extract PR information
        id: pr_info
        run: |
          COMMENT_BODY=$(echo "${{ github.event.comment.body }}")
          SHA=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $1}')
          BRANCH=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $2}')
          echo "SHA=${SHA}" >> $GITHUB_ENV
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
      - name: Debug
        run: |
           echo "Comment body: ${github.event.comment.body}"
           COMMENT_BODY=$(echo "${{ github.event.comment.body }}")
           echo "Extracted comment body: $COMMENT_BODY"
           SHA=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $1}')
           echo "Extracted SHA: $SHA"
           BRANCH=$(echo "$COMMENT_BODY" | grep -oP '/buildkite\s\K.*' | awk '{print $2}')
           echo "Extracted branch: $BRANCH"
           echo "Setting environment variables..."
           echo "SHA=${SHA}" >> $GITHUB_ENV
           echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
           echo "Environment variables set."
      - name: Trigger Buildkite Build
        env:
          BUILDKITE_API_TOKEN: ${{ secrets.bkua_cddacd54a5426d0104266813f7ec3c037a3ade64 }}
        run: |
          curl -X POST "https://api.buildkite.com/v2/organizations/hazenai/pipelines/buildkite-github-action-test/builds" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer bkua_cddacd54a5426d0104266813f7ec3c037a3ade64" \
            -d "{\"commit\":\"${{ env.SHA }}\", \"branch\":\"${{ env.BRANCH }}\"}"
