name: Automation



on:
  push:
    branches:
      - main
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'test')
    uses: ./.github/workflows/main.yml
